version: '3.3'

services:
  php:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=database

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 88:80
    environment:
      PMA_HOST: db:3306
      MYSQL_ROOT_PASSWORD: toor

volumes:
  db_data: